# Generated by Django 6.0.1 on 2026-01-17 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Контакты', max_length=120, verbose_name='Заголовок')),
                ('about', models.TextField(blank=True, verbose_name='О нас / описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный профиль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Профиль контактов',
                'verbose_name_plural': 'Профили контактов',
            },
        ),
        migrations.CreateModel(
            name='ContactItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('phone', 'Телефон'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('address', 'Адрес'), ('website', 'Сайт'), ('other', 'Другое')], max_length=20, verbose_name='Тип')),
                ('label', models.CharField(blank=True, max_length=120, verbose_name='Подпись')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Ссылка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contacts.contactprofile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['order', 'id'],
            },
        ),
    ]
