# Generated by Django 6.0 on 2026-01-20 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='category',
        ),
        migrations.DeleteModel(
            name='CaseCategory',
        ),
    ]
