# Generated by Django 6.0 on 2026-01-20 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_documents_d_slug_3df491_idx_and_more'),
        ('portfolio', '0002_remove_case_category_delete_casecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('title_override', models.CharField(blank=True, max_length=200, verbose_name='Название в кейсе')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Документ в кейсе',
                'verbose_name_plural': 'Документы в кейсах',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='portfoliopage',
            index=models.Index(fields=['order'], name='portfolio_p_order_77e082_idx'),
        ),
        migrations.AddIndex(
            model_name='portfoliopage',
            index=models.Index(fields=['is_published'], name='portfolio_p_is_publ_d35c51_idx'),
        ),
        migrations.AddIndex(
            model_name='portfoliopage',
            index=models.Index(fields=['slug'], name='portfolio_p_slug_95ea63_idx'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_documents', to='portfolio.case', verbose_name='Кейс'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_documents', to='documents.document', verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='case',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='cases', through='portfolio.CaseDocument', to='documents.document', verbose_name='Документы'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['slug'], name='portfolio_c_slug_135123_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['is_published'], name='portfolio_c_is_publ_89f642_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['created_at'], name='portfolio_c_created_19be97_idx'),
        ),
        migrations.AddIndex(
            model_name='casedocument',
            index=models.Index(fields=['order'], name='portfolio_c_order_bf1872_idx'),
        ),
        migrations.AddIndex(
            model_name='casedocument',
            index=models.Index(fields=['is_active'], name='portfolio_c_is_acti_9082e7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='casedocument',
            unique_together={('case', 'document')},
        ),
    ]
