# Generated by Django 6.0 on 2026-01-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='newscategory',
            index=models.Index(fields=['order'], name='news_newsca_order_8ae00b_idx'),
        ),
        migrations.AddIndex(
            model_name='newscategory',
            index=models.Index(fields=['is_active'], name='news_newsca_is_acti_354c69_idx'),
        ),
        migrations.AddIndex(
            model_name='newscategory',
            index=models.Index(fields=['slug'], name='news_newsca_slug_5c0a14_idx'),
        ),
        migrations.AddIndex(
            model_name='newspost',
            index=models.Index(fields=['slug'], name='news_newspo_slug_842a50_idx'),
        ),
        migrations.AddIndex(
            model_name='newspost',
            index=models.Index(fields=['is_published'], name='news_newspo_is_publ_1d02a8_idx'),
        ),
        migrations.AddIndex(
            model_name='newspost',
            index=models.Index(fields=['published_at'], name='news_newspo_publish_406864_idx'),
        ),
        migrations.AddIndex(
            model_name='newspost',
            index=models.Index(fields=['created_at'], name='news_newspo_created_b8775b_idx'),
        ),
    ]
