# Generated by Django 6.0 on 2026-01-20 09:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['slug'], name='documents_d_slug_3df491_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_published', 'is_open'], name='documents_d_is_publ_2519c6_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['access_type'], name='documents_d_access__695462_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_at'], name='documents_d_created_3b0a51_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcategory',
            index=models.Index(fields=['order'], name='documents_d_order_669937_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcategory',
            index=models.Index(fields=['is_active'], name='documents_d_is_acti_c8e63e_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcategory',
            index=models.Index(fields=['slug'], name='documents_d_slug_d17b69_idx'),
        ),
        migrations.AddIndex(
            model_name='documentpurchase',
            index=models.Index(fields=['status'], name='documents_d_status_c02c7d_idx'),
        ),
        migrations.AddIndex(
            model_name='documentpurchase',
            index=models.Index(fields=['created_at'], name='documents_d_created_09b86e_idx'),
        ),
        migrations.AddIndex(
            model_name='documentpurchase',
            index=models.Index(fields=['paid_at'], name='documents_d_paid_at_1d4ad3_idx'),
        ),
    ]
